/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  G4P.setDisplayFont("Consolas", G4P.PLAIN, 20);
  surface.setTitle("Sketch Window");
  label1 = new GLabel(this, 10, 40, 379, 20);
  label1.setText(" xx             xx         xxx  m");
  label1.setOpaque(false);
  label2 = new GLabel(this, 16, 14, 100, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Latitude");
  label2.setOpaque(false);
  label3 = new GLabel(this, 128, 14, 110, 20);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Longitude");
  label3.setOpaque(false);
  label4 = new GLabel(this, 264, 14, 100, 20);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("Altitude");
  label4.setOpaque(false);
  label5 = new GLabel(this, 7, 75, 124, 26);
  label5.setText("No Fix  ");
  label5.setOpaque(false);
  label6 = new GLabel(this, 160, 81, 232, 20);
  label6.setText(" 0 Satellites Active");
  label6.setOpaque(false);
  label7 = new GLabel(this, 35, 129, 274, 20);
  label7.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label7.setText("reporting precision");
  label7.setOpaque(false);
  label8 = new GLabel(this, 53, 158, 298, 20);
  label8.setText("Latitude(N-S)=0.XXXm");
  label8.setOpaque(false);
  label9 = new GLabel(this, 42, 186, 292, 20);
  label9.setText("Longitude(E-W)=0.XXXm");
  label9.setOpaque(false);
  label10 = new GLabel(this, 108, 211, 220, 23);
  label10.setText("Altitude=0.1  m");
  label10.setOpaque(false);
}

// Variable declarations 
// autogenerated do not edit
GLabel label1; 
GLabel label2; 
GLabel label3; 
GLabel label4; 
GLabel label5; 
GLabel label6; 
GLabel label7; 
GLabel label8; 
GLabel label9; 
GLabel label10; 
